# Configure the task for evaluation

server_addr: ningxia

home_env:
  ningxia:
    data_home: /nxchinamobile2/shared/mmbench_datasets

tasks:
  level_1:
    ScienceQA:
      metrics: [acc]
      data:
        train_data: ScienceQA/csv_files/train.csv
        valid_data: ScienceQA/csv_files/val.csv
        test_data: ScienceQA/csv_files/test.csv
      need_finetune: true
      need_evaluate: true
      finetune_params:
        mode: "finetune"
        max_source_length: 1024
        max_target_length: 256
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
        do_valid: false
        # eval_iters: 20
        eval_interval: 500
        strict_eval: true
        eval_batch_size: 10
        do_test: false
      eval_params:
        mode: "inference"
        strict_eval: true
        top_k: 10
        top_p: 0.4
        temperature: 0.8
    
  # level_2:

  # level_3:
    # HalVQA:
    #   data:
    #     train:
    #     val:
    #     test: 
    #   metrics: [acc]
    #   params: 
      