# Configure the task for evaluation

server_addr: wulan

home_env:
  wulan:
    data_home: /mnt/shared/img_datasets/mmbench_datasets/processed
  zhongwei:
    data_home: /share/img_datasets/mmbench_datasets/processed_mmbench_20231120
  zhongwei2:
    data_home: /zhipu-data/img_datasets/mmbench_datasets/processed_mmbench_20231120

tasks:
  level_1:
    Infer:
      test_data: /zhipu-data/img_datasets/cleaned_rlhf/raw_data/20231218###test

    ScienceQA:
      train_data: ScienceQA/train###train
      valid_data: ScienceQA/val###val
      test_data: ScienceQA/test###test
    
    Visual7W:
      train_data: Visual7W/train###train
      valid_data: Visual7W/val###val
      test_data: Visual7W/test###test
    
    OCRVQA:
      train_data: OCR-VQA/train###train
      valid_data: OCR-VQA/val###val
      test_data: OCR-VQA/test###test
    
    TDIUC:
      train_data: TDIUC/train###train
      test_data: TDIUC/val###test
    
    TextVQA:
      train_data: TextVQA/train###train
      test_data: TextVQA/val###test
      upload_data: [TextVQA/test]
      
    GQA:
      train_data: GQA/train###train
      valid_data: GQA/val###val
      test_data: GQA/testdev_balanced###test
    
    NoCaps:
      test_data: NoCaps/val###test
    
    VQAv2:
      train_data: VQAV2/train###train
      test_data: VQAV2/val###test
      upload_data: [VQAV2/test]

    OCR_EN:
      train_data: TAL_OCR_ENG/test###train
      test_data: TAL_OCR_ENG/test###test
    
    OCR_ZH:
      train_data: TAL_OCR_CHN/train###train
      test_data: TAL_OCR_CHN/test###test

    COCO:
      train_data: COCO/train###train
      valid_data: COCO/val###val
      test_data: COCO/val###test

    STVQA:
      train_data: STVQA/train###train
      upload_data: [STVQA/test_task_3]

    FlickrCap:
      train_data: FlickrCap/train###train
      valid_data: FlickrCap/val###val
      test_data: FlickrCap/test###test

    ChartQA:
      train_data: ChartQA/train###train
      valid_data: ChartQA/val###val
      test_data: ChartQA/test###test

    RefCOCO:
      train_data: RefCOCO/train###train
      valid_data: RefCOCO/refcoco-val###val
      test_data: RefCOCO/test###test

    DocVQA:
      train_data: DocVQA/train###train
      valid_data: DocVQA/val###val
      test_data: DocVQA/test###test

    VizWizVQA:
      train_data: VizWiz-VQA/train###train
      valid_data: VizWiz-VQA/val###val
      test_data: VizWiz-VQA/test###test
    
    TallyQA:
      train_data: TallyQA/train###train
      test_data: TallyQA/test###test
    
  level_2:
    OKVQA:
      train_data: OK-VQA/train###train
      test_data: OK-VQA/val###test

  level_3:
    HalVQA:
      train_data: HalVQA/train###train
      test_data: HalVQA/test###test
      
    TouchStone:
      test_data: TouchStone/test###test

    TouchStoneChinese:
      test_data: TouchStone/test-zh###test
    
    AlignMMBench:
      train_data: AlignMMBench/train###train
      valid_data: AlignMMBench/valid###valid
      test_data: AlignMMBench/test###test