# Configure the data paths for evaluation

level_1:

  VQAv2:
    # annotation files
    anns_paths: /nxchinamobile2/shared/instruction_data/evaluation/vqav2_sampled.json
    # directory of images
    img_dir: /nxchinamobile2/shared/img_datasets/MSCOCO/MSCOCO2014/val2014
    # which metrics to be used for measurements, supporting [vqa_acc, ...]
    metrics: [vqa_acc, gpt35_metric]
    # whether to be used for current evaluation
    eval: True

  Flickr30kEntities:
    anns_paths: /nxchinamobile2/shared/instruction_data/evaluation/flickr3kent_sampled.jsonl
    img_dir: /nxchinamobile2/shared/img_datasets/shikra/flickr30k-images
    eval: true
    metrics: [grounding]
    n_samples: 500
    seed: 9271

  RefCOCO:
    anns_paths: /nxchinamobile2/shared/instruction_data/evaluation/refcoco_sampled.jsonl
    img_dir: /nxchinamobile2/shared/img_datasets/MSCOCO/MSCOCO2014/train2014
    eval: true
    metrics: [grounding]
    n_samples: 500
    seed: 9271

  RefCOCOp:
    anns_paths: /nxchinamobile2/shared/instruction_data/evaluation/refcoco+_sampled.jsonl
    img_dir: /nxchinamobile2/shared/img_datasets/MSCOCO/MSCOCO2014/train2014
    eval: true
    metrics: [grounding]
    n_samples: 500
    seed: 9271

  RefCOCOg:
    anns_paths: /nxchinamobile2/shared/instruction_data/evaluation/refcocog_sampled.jsonl
    img_dir: /nxchinamobile2/shared/img_datasets/MSCOCO/MSCOCO2014/train2014
    eval: true
    metrics: [grounding]
    n_samples: 500
    seed: 9271

  TDIUC:
    anns_paths: /nxchinamobile2/shared/instruction_data/evaluation/tdiuc_sampled.jsonl
    img_dir: /nxchinamobile2/shared/img_datasets/MSCOCO/MSCOCO2014/val2014
    eval: true
    metrics: [vqa_acc]
    n_samples: 500
    seed: 71

  ScienceQA:
    anns_paths: /nxchinamobile2/shared/instruction_data/ScienceQA/data/scienceqa/problems.json
    img_dir: /nxchinamobile2/shared/instruction_data/ScienceQA/test
    eval: True
    metrics: [acc]
  
  OCRVQA:
    anns_paths: /nxchinamobile2/shared/instruction_data/MultiInstruct/raw/OCR-VQA/dataset.json
    img_dir: /nxchinamobile2/shared/instruction_data/MultiInstruct/raw/OCR-VQA/amazon_images_folder
    metrics: [acc]
    eval: True

  HalVQA:
    anns_paths: /nxchinamobile2/shared/instruction_data/MultiInstruct/raw/hal_val_sample/data_test.jsonl
    img_dir: /nxchinamobile2/shared/instruction_data/MultiInstruct/raw/hal_val_sample/images
    metrics: [acc]
    eval: True

  # visual7w:
  #   anns_paths: [path/to/annotations]
  #   img_dir: path/to/images
  #   metrics: [vqa_acc, gpt3.5]
  #   eval: True

# level_2:

#   ok_vqa:
#     anns_paths: [path/to/annotations]
#     img_dir: path/to/images
#     metrics: [vqa_acc, gpt3.5]
#     eval: True

# level_3:
