# Configure the task for evaluation

server_addr: zhongwei

home_env:
  ningxia:
    data_home: /nxchinamobile2/shared/mmbench_datasets
  wulan:
    data_home: /mnt/shared/img_datasets/mmbench_datasets
  zhongwei:
    data_home: /share/img_datasets/mmbench_datasets

tasks:
  level_1:
    ScienceQA:
      data:
        train_data: processed/ScienceQA/train###train
        valid_data: processed/ScienceQA/val###val
        test_data: processed/ScienceQA/test###test
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 1000
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_iters: 100
        eval_interval: 500
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8
    
    Visual7W:
      data:
        train_data: processed/Visual7W/train###train
        valid_data: processed/Visual7W/val###val
        test_data: processed/Visual7W/test###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 1000
      finetune_params:
        log_interval: 20
        train_iters: 5000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 1000
        split: "1"
      eval_params:
        eval_iters: 200
        eval_interval: 1000
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8
    
    OCRVQA:
      data:
        train_data: processed/OCR-VQA/train###train
        valid_data: processed/OCR-VQA/val###val
        test_data: processed/OCR-VQA/test###test
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
      finetune_params:
        log_interval: 20
        train_iters: 5000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 1000
        split: "1"
      eval_params:
        eval_iters: 200
        eval_interval: 1000
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8
    
    TDIUC:
      data:
        train_data: processed/TDIUC/train###train
        test_data: processed/TDIUC/val###test
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
      finetune_params:
        log_interval: 20
        train_iters: 5000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 1000
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8
    
    TextVQA:
      data:
        train_data: processed/TextVQA/train###train
        test_data: processed/TextVQA/val###test
        upload_data: [processed/TextVQA/test]
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8
      
    GQA:
      data:
        train_data: processed/GQA/train###train
        valid_data: processed/GQA/val###val
        test_data: processed/GQA/testdev_balanced###test
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
      finetune_params:
        log_interval: 20
        train_iters: 10000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 1000
        split: "1"
      eval_params:
        eval_iters: 200
        eval_interval: 1000
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8
    
    NoCaps:
      data:
        test_data: processed/NoCaps/val###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 1000
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8
    
    VQAv2:
      data:
        train_data: processed/VQAV2/train###train
        test_data: processed/VQAV2/val###test
        upload_data: [processed/VQAV2/test]
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8
    
    COCO:
      data:
        train_data: processed/COCO/train###train
        valid_data: processed/COCO/val###val
        test_data: processed/COCO/val###test
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8

    STVQA:
      data:
        train_data: processed/STVQA/train###train
        upload_data: [processed/STVQA/test_task_3]
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8

    FlickrCap:
      data:
        train_data: processed/FlickrCap/train###train
        valid_data: processed/FlickrCap/val###val
        test_data: processed/FlickrCap/test###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8

    ChartQA:
      data:
        train_data: processed/ChartQA/train###train
        valid_data: processed/ChartQA/val###val
        test_data: processed/ChartQA/test###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8

    RefCOCO:
      data:
        train_data: processed/RefCOCO/train###train
        valid_data: processed/RefCOCO/refcoco-val###val
        test_data: processed/RefCOCO/test###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8

    DocVQA:
      data:
        train_data: processed/DocVQA/train###train
        valid_data: processed/DocVQA/val###val
        test_data: processed/DocVQA/test###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8

    VizWizVQA:
      data:
        train_data: processed/VizWiz-VQA/train###train
        valid_data: processed/VizWiz-VQA/val###val
        test_data: processed/VizWiz-VQA/test###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8
    
    TallyQA:
      data:
        train_data: processed/TallyQA/train###train
        test_data: processed/TallyQA/test###test
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8
    
  level_2:
    OKVQA:
      data:
        train_data: processed/OK-VQA/train###train
        test_data: processed/OK-VQA/val###test
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
        no_prompt: true
      finetune_params:
        log_interval: 20
        train_iters: 20000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        eval_batch_size: 1
        top_k: 1
        top_p: 0.4
        temperature: 0.8

  level_3:
    HalVQA:
      data:
        train_data: processed/HalVQA/train###train
        test_data: processed/HalVQA/test###test
      need_finetune: true
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: false
        train_data_load_mode: epoch_round
        block_size: 500
      finetune_params:
        log_interval: 20
        train_iters: 2000
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        block_size: 500
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8
    
    COM:
      need_finetune: false
      need_evaluate: true
      data_params:
        max_source_length: 1625
        max_target_length: 423
        iterable_dataset: true
        block_size: 500
      finetune_params:
        log_interval: 20
        train_iters: 500
        block_size: 500
        resume_dataloader: true
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 500
        split: "1"
      eval_params:
        eval_interval: 0
        block_size: 500
        eval_batch_size: 1
        top_k: 10
        top_p: 0.4
        temperature: 0.8