# Configure the data path for evaluation
models:
  Emu2:
    model_name: BAAI/Emu2
    num_devices: 1

  Emu2_Chat:
    model_name: BAAI/Emu2-Chat
    num_devices: 1

  XComposer:
    model_name: Shanghai_AI_Laboratory/internlm-xcomposer-vl-7b
    num_devices: 1

  XComposer2:
    model_name: Shanghai_AI_Laboratory/internlm-xcomposer2-vl-7b
    num_devices: 1

  QwenVL: 
    model_name: qwen/Qwen-VL
    num_devices: 1

  QwenVLChat: 
    model_name: qwen/Qwen-VL-Chat
    num_devices: 1

  YiVL_6B:
    model_name: 01ai/Yi-VL-6B
    num_devices: 1

  YiVL_34B:
    model_name: 01ai/Yi-VL-34B
    num_devices: 1

  QwenVLPlus:
    model_name: qwen-vl-plus

  QwenVLMax:
    model_name: qwen-vl-max
    
# Configure the data path for evaluation

tasks:
  level_1:
    Infer:
      datapath: [/zhipu-data/img_datasets/cleaned_rlhf/raw_data/20231218###test]
      metrics: []

    ScienceQA:
      datapath: [ScienceQA/test###test]
      metrics: []
    
    Visual7W:
      datapath: [Visual7W/test###test]
      metrics: []
    
    OCRVQA:
      datapath: [OCR-VQA/test###test]
      metrics: []
    
    TDIUC:
      datapath: [TDIUC/val###test]
      metrics: []
    
    TextVQA:
      datapath: [TextVQA/val###test,TextVQA/test###upload]
      metrics: []
      
    GQA:
      datapath: [GQA/testdev_balanced###test]
      metrics: []
    
    NoCaps:
      datapath: [NoCaps/val###test]
      metrics: []

    VQAv2:
      datapath: [VQAV2/val###test,VQAV2/test###upload]
      metrics: []

    OCR_EN:
      datapath: [TAL_OCR_ENG/test###test]
      metrics: []
    
    OCR_ZH:
      datapath: [TAL_OCR_CHN/test###test]
      metrics: []

    COCO:
      datapath: [COCO/val###test]
      metrics: []

    STVQA:
      datapath: [STVQA/test_task_3]
      metrics: []

    FlickrCap:
      datapath: [FlickrCap/test###test]
      metrics: []

    ChartQA:
      datapath: [ChartQA/test###test]
      metrics: []

    RefCOCO:
      datapath: [RefCOCO/refcoco-val###val,RefCOCO/test###test]
      metrics: []

    DocVQA:
      datapath: [DocVQA/test###test]
      metrics: []

    VizWizVQA:
      datapath: [VizWiz-VQA/test###test]
      metrics: []
    
    TallyQA:
      datapath: [TallyQA/test###test]
      metrics: []
    
  level_2:
    OKVQA:
      datapath: [OK-VQA/val###test]
      metrics: []

  level_3:
    TouchStone:
      datapath: [TouchStone/test###upload]
      metrics: []

    TouchStoneChinese:
      datapath: [TouchStone/test-zh###upload]
      metrics: []
    
    AlignMMBench:
      datapath: [alignmmbench###upload]
      metrics: []

    MMMU:
      datapath: [MMMU/validation###val]
      metrics: []

    MMBench:
      datapath: [MMBench/MMBench_DEV_CN###dev_cn,MMBench/MMBench_DEV_EN###dev_en]
      metrics: []