# Configure the data path for evaluation

tasks:
  level_1:
    Infer:
      datapath: [/zhipu-data/img_datasets/cleaned_rlhf/raw_data/20231218###test]
      metrics: []

    ScienceQA:
      datapath: [ScienceQA/test###test]
      metrics: []
    
    Visual7W:
      datapath: [Visual7W/test###test]
      metrics: []
    
    OCRVQA:
      datapath: [OCR-VQA/test###test]
      metrics: []
    
    TDIUC:
      datapath: [TDIUC/val###test]
      metrics: []
    
    TextVQA:
      datapath: [TextVQA/val###test,TextVQA/test###upload]
      metrics: []
      
    GQA:
      datapath: [GQA/testdev_balanced###test]
      metrics: []
    
    NoCaps:
      datapath: [NoCaps/val###test]
      metrics: []

    VQAv2:
      datapath: [VQAV2/val###test,VQAV2/test###upload]
      metrics: []

    OCR_EN:
      datapath: [TAL_OCR_ENG/test###test]
      metrics: []
    
    OCR_ZH:
      datapath: [TAL_OCR_CHN/test###test]
      metrics: []

    COCO:
      datapath: [COCO/val###test]
      metrics: []

    STVQA:
      datapath: [STVQA/test_task_3]
      metrics: []

    FlickrCap:
      datapath: [FlickrCap/test###test]
      metrics: []

    ChartQA:
      datapath: [ChartQA/test###test]
      metrics: []

    RefCOCO:
      datapath: [RefCOCO/refcoco-val###val,RefCOCO/test###test]
      metrics: []

    DocVQA:
      datapath: [DocVQA/test###test]
      metrics: []

    VizWizVQA:
      datapath: [VizWiz-VQA/test###test]
      metrics: []
    
    TallyQA:
      datapath: [TallyQA/test###test]
      metrics: []
    
  level_2:
    OKVQA:
      datapath: [OK-VQA/val###test]
      metrics: []

  level_3:
    TouchStone:
      datapath: [TouchStone/test###upload]
      metrics: []

    TouchStoneChinese:
      datapath: [TouchStone/test-zh###upload]
      metrics: []
    
    AlignMMBench:
      datapath: [alignmmbench###upload]
      metrics: []