# Configure the task for evaluation

server_addr: ningxia

home_env:
  ningxia:
    data_home: /nxchinamobile2/shared/mmbench_datasets

tasks:
  level_1:
    ScienceQA:
      data:
        train: ScienceQA/web_dataset/train
        val: ScienceQA/web_dataset/val
        test:  
      metrics: [acc]
      params:
        checkpoint_activations: true
        train_iters: 2000
        resume_dataloader: true
        distributed_backend: nccl
        lr_decay_style: cosine
        warmup: 0.02
        save_interval: 2000
        strict_eval: true
        # save: $ME_HOME
        split: 1
        eval_batch_size: 10
        lr: 100
        fp16: true
        iterable_dataset: true
    
  level_2:

  level_3:
    HalVQA:
      data:
        train:
        val:
        test: 
      metrics: [acc]
      processor: 
      